[package]
name = "naive_hashmap"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "naive_interpreter"
doc = false

[dependencies]
rand = "0.9.0"

[dev-dependencies]
quickcheck = "0.6.0"
criterion = "0.5.1"
