valgrind-cachegrind-special:
	valgrind --tool=cachegrind --branch-sim=yes target/release/specialized

valgrind-cachegrind-std:
	valgrind --tool=cachegrind --branch-sim=yes target/release/standard

valgrind-cachegrind-naive:
	valgrind --tool=cachegrind --branch-sim=yes target/release/naive
